expname: mamba

model:
  name: mamba
  input_size: 16
  d_model: 64
  n_layers: 2
  parallel: true

task:
  name: randomcopy
  T: 4096
  block_T: null
  vocab_size: 16
  len_sequence: 16

data:
  n_train: 60000
  n_eval: 10000
  batch_size: 64

train:
  grad_steps: 1000
  log_interval: 1000
  patience: 10

optim:
  name: adam
  lr: 1e-4
  eps: 1e-8
  use_amp: False
  clip: null

seed:
  data: 1234
  train: 9999

device_id: cuda:1

log_dir: log

checkpoint_model: null

eval_only: false

param_count_only: false
